name: Keep Streamlit alive

on:
  schedule:
    - cron: '0 */2 * * *' # every 2 hours
  workflow_dispatch: # allow manual trigger

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Ping Streamlit app
        run: curl -sfo /dev/null https://clinical-trial-intelligence.streamlit.app
